project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - publications.qmd
    - cv.qmd

website:
  title: "Bahram Behzadian"
  site-url: "https://buiksat.github.io"
  search: false
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
